// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstCIxHUAqz7p9YPQqPwWcEMSIyeeOEUE',
    appId: '1:130981486129:web:96970a7644e1d05606bf10',
    messagingSenderId: '130981486129',
    projectId: 'food-fif',
    authDomain: 'food-fif.firebaseapp.com',
    storageBucket: 'food-fif.firebasestorage.app',
    measurementId: 'G-WX0L6QQEZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgTmuMD4AZ4NWLM10ZbeiMLNTNu0DyeI',
    appId: '1:130981486129:android:85ae31f186c07cbf06bf10',
    messagingSenderId: '130981486129',
    projectId: 'food-fif',
    storageBucket: 'food-fif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-W6Umf491wA8pAD7GI1PwRzNmxW1_xPI',
    appId: '1:130981486129:ios:dd05c62251342c9106bf10',
    messagingSenderId: '130981486129',
    projectId: 'food-fif',
    storageBucket: 'food-fif.firebasestorage.app',
    iosBundleId: 'com.example.foodChifa',
  );
}
